# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ecommerceApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ecommerceApp

  target 'ecommerceAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ecommerceApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ecommerceApp-tvOS

  target 'ecommerceApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
